'use strict';

const {extractJson} = require('@iota/extract-json');
const config = require('config');
const zmq = require('zeromq');
const sock = zmq.socket('sub');
const Iota = require('../core/iota');

console.log(config);

const zmqNodeAddress = 'tcp://zmq.devnet.iota.org:5556';

const members = [];
const payments = [];
const data = [];

module.exports = async () => {
    const iota = new Iota();
    await iota.initialize();
    const provider = iota.getProvider();

    // Address deterministic generation
    const dataAddress = await iota.generateAddress(config.seed, 0);
    console.log(dataAddress);

    sock.connect(zmqNodeAddress);
    console.log('Connected to ' + zmqNodeAddress);
    // sock.subscribe('sn'); // sn = confirmed tx
    sock.subscribe(dataAddress); // subscribe to data address
    console.log(`Subscribed to ${dataAddress} updates...`);
    sock.on('message', async (msg) => {
        let data = msg.toString().split(' ');
        console.log(`Tx address: ${data[0]}`);
        console.log(`Tx hash: ${data[1]}`);
        console.log(`Tx milestone: ${data[2]}`);
        console.log(`Tx type: ${data[3]}`);
        const a = await provider.getTransactionObjects([data[1]]);
        console.log(a);
        console.log(extractJson(a))
        /*
        [{
            hash: 'ISVTKARPY9OQDADCRVVGZHIGVLEXJOBGBRBBN9MIRSUEUURSMMYSOFWLWZADRLTJOYLIEPOTEWDXDB999',
            signatureMessageFragment: 'DF9XKHYCSZWQXHIGKSOXMXINPOBPXGBFXQJUCXXDPZBAPIOSSIAFNOBCWTSXAWJAAJNKFMWVJBLJTHFTDJWFEXVDDJBJVXZ9X9SKGAHTKTFTLMBNJWYEBNXHRTLNFJVPWQQXEUVVWREKGFPFNVQINTJDDBFLYVAKIYGCLFFTYTIT99IDROCIGGRLTVTAPXTXDRSQ9QHEFVTMEMVKMOUXH9KFTJXIZPHSVTHLBTKGG9RRRWOFOLDNMZYKRFLEEJHZCRZHHEWDTTN9MLZLYVORTGNUFIURFKYYWHFQBIOHGD9SMCWHWOBLYHXUKDYFPHJXADOBNQBTTZMZOREBCAEFXQTGOYXXVYMDYVRPJMWOW9ATV9VODO9DOV9QTYXRIGYNDDWJAV9FDWJIMKAGAR9GDWUMTJTHUVTAZEQTZLJ9MJQSGUFAB9QEZFLZMFEETROXMEQGUZQFDIKADSGWNGFMCVU9MAUKIYJPABWLXDTIYFKVSOT9IF9UPMG9USWWXBIXPMMXPWUFCMGOFCSXUKKXNXXZRYSPDITVMBJEGQDCSFULGWGLOHN9SSD9GNDFX9FFMZBYNHAGLVCYELBHMLQXCOQSSPRBGFFNIXIQBIJAHXETVLEXDWMPTGVHSNTPKAFCFSA9TNJWRH9NUREMVPAXEGJGJEQG9NRUJXNBUOVMROT9JCTMZLWNBYB9LGBQJPKQFVCBRDZVSLVTPDYANWLMVOKQDRNYJWQAHSUCXSKJZXTITGMKQOYCATMTAISWZZMLNMTKNUPA9OZGZK9IJZLWMXUMXWIYKYSGZTKUPLSOJDYAORDBTHBIOWHBHPZNLAISCSUNV99PY9X9IJZZXRZGRXOFKNPZFBXRGENIQJWEHAKKDGFZVPZVFZKYPMBCAYY9LYMIZADTOCCZNHNDRXZDIWETFTPBXOHFWIUSTUNVZICCQF9LVNQXHEXWBPCWNCW9AKOQVFWG9JVDQVOATJUBGCWB9J9XZELWZVBDQJOOZGTAYLN9ORLBMPVFSGVASUJ9VBXQONHDCECWOERKJLFCMCUJEVJMDJOKIZBEZSMMTQG9RMKSGXUPVIXXUTDZEPKAO9XRJUNDHKPYEFEWKGLADEXITGEQVUYQVJFMR9RSOIEGGYMA9TQITIOKDKZLXPOLBOSSWJXFEEIXUASNINRDPMDKZOCQDGBDLRYQPWDNCNFXCBNENIFJHKTHXGOAIEAQOMNXASDEMOQJKEZU9TTYVPKEEBD9NOTHYLZJMCVSQVMI9TZJSDASVNIUEDPNPDGEBUFFJJSJSOLDZMQAUUPSDNKERPVWX9KICOPDFHLXWBKOODXBTE9KOYHUCLVGK9ZACHBQBNZJYECUNTLNHYALGKLQHBLEQ9LNWSEYVXYBTXCMZAWRAMGQRKBGPPPVELMFFQNFBY9DUKYVAJNDPJDJMSUFNQDVIEMCUHVFY9JWSSFWIBJYVD9GXNQWYNWSJRBVXCAYOQRKITAOLCDMCSWDEEGKNI9J9EIV9SUVQQCZWROFZMFYPIOMHQBNWETZ9RCQQQCFTULQQWOMTPMMTZVZSRMDIRLOHQYLJYRH9MRXXDOZKBZPVPNNPWAQCOEFCPDQIYOEJGHNJUOEBINRHOICGPUWPNKVSONWFIBFPQYHZVKVDTVNKJANCKTDOJGIAVDSVFCZDKQEULEXROGHOVVM99HHVRONHOBIMAKAYDYXHPTKS9YKUPIKEETFRQMAV9YXYBONYJDTLJUYCFGPKEALLMNKWCZAAURQZFWYWRDOPMRKVZFBIHIOUCUFHTSGCCCOA9IYWQDKRCSXROWCZOOXGTTJDTBWPIVN9EYKBCETHJQ9EQVQHNQYAUYTVQZWDJLZOIWUIMCIJFD9VULRHWXHZWLD9BTAPMAPQYBLUVHAKDS9ZPND9RGVTWKCSOJSGKZNOGTBMSWPYLVQOWEFOPSDHG9BMVMF9WS9YOPKCODTMFZHUQHDJLNQBVLQJOELXTWRXJITTDEKUQV9NULQJMGHGDJKFVEBR9VFCLWVKOSADO9RTDNWF9JI9PCSOOAWMRYBIFJ9XBGGTHXWGJCEVFA9JRW9MFEOKNZIOOUHJZHVQMTJUEOKYBSK9WUSNZXJRL9KBDPIWOTIYKMNYWXXWOXRD9JXOPQEPW9ZRUZUOQVKMPPYYLWXI9DPXCEPEIHXYCTFMWLQFBHJDFW',
            address: 'VTMPVYGXMIMJHYROFIHYBODLIXZYMAUTOWVEURKSDSLEHPENKSCWXVJJWIJPBHVAZNFHIDNVTUBIYMCB9',
            value: -500,
            obsoleteTag: '999999999999999999999999999',
            timestamp: 1565295311,
            currentIndex: 1,
            lastIndex: 2,
            bundle: 'ZWDZKDJGL9TTDNPRLAVBGTRYPKDARUDMYJN9OCEFHCJKBSPILKBDFIRM99XJTLKZVHBHXZJVKIEQDAPD9',
            trunkTransaction: 'THLKNVWKSHACREMSH9MEXEOILKGWWDWJFFFLHPXQQIPTLPQIGUMVEPFHEVRAXA9FKTZPPJECFZFTIB999',
            branchTransaction: 'YEUFZXZJXSO9VJWCNOLRQNPMRMBYUFUGPYUNYBZDFJMEWJIIWBPATUJ9HCUVUEBVOLHGJZXQEEXBC9999',
            tag: '999999999999999999999999999',
            attachmentTimestamp: 1565295315328,
            attachmentTimestampLowerBound: 0,
            attachmentTimestampUpperBound: 3812798742493,
            nonce: 'XKPJXIRFHDB9GCHUMZOGKQVNTEX'
        }]
         */
    });
};
